rango/urls.py
from django.urls import path
from rango import views
from rango.views import AboutView, AddCategoryView, IndexView, ShowCategoryView, RegisterProfile, GoToUrl, AddPage, ProfileView, ListProfilesView, LikeCategoryView, SearchAddPageView

app_name = 'rango'
LOGIN_URL = 'rango:login'

urlpatterns = [
    path('',views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('category/<slug:category_name_slug>/', views.ShowCategoryView.as_view(), name='show_category'),
    path('add_category/', views.AddCategoryView.as_view(), name='add_category'),
    path('category/<slug:category_name_slug>/add_page/', AddPage.as_view(), name='add_page'),
    path('like_category/', views.LikeCategoryView.as_view(),name='like_category'),
    path('suggest/', views.CateforySuggestionView.as_view(),name='suggest'),
    path('search/', views.search, name='search'),
    path('search_add_page/', views.SearchAddPageView.as_view(), name='search_add_page'),
    path('goto/', views.GoToUrl.as_view(), name='goto'),
    path('register_profile/', views.RegisterProfile.as_view(), name='register_profile'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profiles/', views.ListProfilesView.as_view(), name='list_profiles'),
    # path('register/', views.register, name='register'),
    # path('login/', views.user_login,name='login'),
    path('restricted/', views.restricted, name='restricted'),
    # path('logout/', views.user_logout, name='logout'),
]

tango_with_django_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include, reverse
from django.conf import settings
from django.conf.urls.static import static
from rango import views
from registration.backends.simple.views import RegistrationView

class MyRegistrationView(RegistrationView):
    def get_success_url(self, user):
        return reverse('rango:register_profile')

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('rango/', include('rango.urls')),
    # The above maps any URLs starting with rango/ to be handled by rango
    path('admin/', admin.site.urls),
    path('accounts/register/',MyRegistrationView.as_view(),name='registration_register'),
    path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
    NAME_MAX_LENGTH = 128

    name = models.CharField(max_length=NAME_MAX_LENGTH, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

class Page(models.Model):
    TITLE_MAX_LENGTH = 128
    URL_MAX_LENGTH = 200

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=TITLE_MAX_LENGTH)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

class UserProfile(models.Model):
    # links UserProfile with User Model instance(association)
    # construct one-to-one relationship with User model
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additional attributes we wish to include(blank=True)
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        #return meaningful string
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=Category.NAME_MAX_LENGTH,help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)

    # An inline class to provide additional information on the form
    class Meta:
        # Provide an relation bet ModelForm and a model
        # recv user defined category name 
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=Page.TITLE_MAX_LENGTH,help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=Page.URL_MAX_LENGTH,help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        # Provide association
        model = Page


        # what fields do we want to include in our form?
        # This way we donot need each field in the model.
        # some may allow NULL values, we donot want to include NULL
        
        # here we hiding the FK
        # we can either exclude the category field from the form
        exclude = ('category',)
        
        # or specify the fields to include('donot include the categoty field')
        # here display 3 attr in the form
        # fields =('title','url','views')

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If url is not empty & donot start with 'http://'
        #then prepend 'http://'
        if url and not url.startswith('http://'):
            url = f'http://{url}'
            cleaned_data['url'] = url

        return cleaned_data

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username','email','password',)

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website','picture',)

rango/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, Http404
from django.urls import reverse
from rango.models import Category, Page, UserProfile
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from datetime import datetime
from rango.bing_search import run_query
from rango.google_search import run_google_search
from django.views import View
from django.utils.decorators import method_decorator


class SearchAddPageView(View):
    @method_decorator(login_required)
    def get(self, request):
        category_id = request.GET['category_id']
        title = request.GET['title']
        url = request.GET['url']
        
        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse('Error - category not found.')
        except ValueError:
            return HttpResponse('Error - bad category ID.')
        
        p = Page.objects.get_or_create(category=category,title=title,url=url)
        pages = Page.objects.filter(category=category).order_by('-views')
        return render(request, 'rango/page_listing.html', {'pages': pages})

def get_category_list(max_results=0, starts_with=""):
    """ 
    optimise static search functionality
    return a list of categories match the user query<starts_with> ---> query results
    helper method for CateforySuggestionView
    """
    category_list = []

    if starts_with:
    # using the filter method to return a filtered set within all the categories
        category_list = Category.objects.filter(name__istartswith=starts_with)
    if max_results > 0:
        if len(category_list) > max_results:
            category_list = category_list[:max_results]
    return category_list

class CateforySuggestionView(View):
    # /rango/suggest/
    """ 
    take user query(suggestion), return top 8 results
    suggestion - > user query input
    """
    def get(self, request):
        if 'suggestion' in request.GET:
            suggestion = request.GET['suggestion']
        else:
            suggestion = ''
        
        # acquire the filetered categories
        category_list = get_category_list(max_results=8,
        starts_with=suggestion)
        if len(category_list) == 0:
            # no query results , default displaying all the category(after ranked)
            category_list = Category.objects.order_by('-likes')
            
        return render(request,'rango/categories.html',{'categories': category_list})


class LikeCategoryView(View):
    @method_decorator(login_required)
    def get(self, request):
        context_dict = {}
        # exam the request.GET dict,pick out the category
        # /rango/like_category/?category_id=1
        category_id = request.GET.get('category_id')
        try:
            category = Category.objects.get(id=int(category_id))
        except Category.DoesNotExist:
            return HttpResponse(-1)
        except ValueError:
            return HttpResponse(-1)

        category.likes = category.likes+1
        category.save()
        # do not render the entire page, using ajax
        return HttpResponse(category.likes)

class ListProfilesView(View):
    @method_decorator(login_required)
    def get(self, request):
        profiles = UserProfile.objects.all()
        return render(request,
        'rango/list_profiles.html',
        {'user_profile_list': profiles})

class ProfileView(View):
    # avoid repeating [DRY]
    def get_user_details(self, username):
        try:
            user = User.objects.get(username=username)
        except User.DoesNotExist:
            return None
        
        user_profile = UserProfile.objects.get_or_create(user=user)[0]
        # current seleted detailed form
        form = UserProfileForm({'website': user_profile.website,'picture': user_profile.picture})
        return (user, user_profile, form)

    @method_decorator(login_required)
    def get(self, request, username):
        # username from url, paramised view
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))
        context_dict = {'user_profile': user_profile,
        'selected_user': user,
        'form': form}
        return render(request, 'rango/profile.html', context_dict)
    
    # update profile
    @method_decorator(login_required)
    def post(self, request, username):
         # username from url, paramised view
        try:
            (user, user_profile, form) = self.get_user_details(username)
        except TypeError:
            return redirect(reverse('rango:index'))
        
        form = UserProfileForm(request.POST, request.FILES, instance=user_profile)
        if form.is_valid():
            # refresh the form and commit 
            form.save(commit=True)
            return redirect('rango:profile', user.username)
        else:
            print(form.errors)
            # return old details
            context_dict = {'user_profile': user_profile,
            'selected_user': user,
            'form': form}
            return render(request, 'rango/profile.html', context_dict)

class RegisterProfile(View):
    @method_decorator(login_required)
    def post(self,request):
        context_dict = {}
        form = UserProfileForm()
        form = UserProfileForm(request.POST, request.FILES)
        # check whether all the form fields are filled correctly
        if form.is_valid():
            # give the time to manipulate the new instance before commiting
            user_profile = form.save(commit=False)
            # refresh current user
            user_profile.user = request.user
            user_profile.save()
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)

        context_dict = {'form':form}
        return render(request, 'rango/profile_registration.html', context_dict)
    
    @method_decorator(login_required)
    def get(self,request):
        form = UserProfileForm()
        context_dict = {'form':form}
        return render(request, 'rango/profile_registration.html', context_dict)

@login_required
def register_profile(request):
    form = UserProfileForm()

    if request.method == 'POST':
        form = UserProfileForm(request.POST, request.FILES)
        # check whether all the form fields are filled correctly
        if form.is_valid():
            # give the time to manipulate the new instance before commiting
            user_profile = form.save(commit=False)
            # refresh current user
            user_profile.user = request.user
            user_profile.save()
            return redirect(reverse('rango:index'))
        else:
            print(form.errors)
    
    # GET, a blank form to fill out
    context_dict = {'form':form}
    return render(request, 'rango/profile_registration.html', context_dict)

    # # capture details of USerProfile instance
    # # for rendering
    # # user = UserProfile
    # context_dict = {}
    # context_dict['name'] = request.user
    # try:
    #     user = UserProfile.objects.get(id=request.user.id)
    #     context_dict['url'] = user.website
    #     context_dict['img'] = user.picture
    # except:
    #     context_dict['url'] = None
    #     context_dict['img'] = None

    # all_user = UserProfile.objects.all()
    # context_dict['all'] = all_user
    # return render(request,"rango/profile.html",context_dict)


    context_dict = {}
    try:
        user = UserProfile.objects.get(id=user.id)
        context_dict['name'] = user
        context_dict['url'] = user.website
        context_dict['img'] = user.picture
    except:
        context_dict['url'] = None
        context_dict['img'] = None

    all_user = UserProfile.objects.all()
    context_dict['all'] = all_user
    print("all",context_dict)

    return render(request,"rango/showp.html",context = context_dict)

class GoToUrl(View):

    def get(self, request):
        page_id = None
        page_id = request.GET.get('page_id')
        try:
            # pick the page
            page = Page.objects.get(id=page_id)

            # Unknown page
            if page==None:
                return redirect(reverse('rango:index'))
            
            # increment the views field of this page, and save
            page.views = page.views + 1
            page.save()
        except:
            return redirect(reverse('rango:index'))
        return redirect(page.url)

def goto_url(request):
    page_id = None
    if request.method == 'GET':
        page_id = request.GET.get('page_id')
        try:
            # pick the page
            page = Page.objects.get(id=page_id)

            # Unknown page
            if page==None:
                return redirect(reverse('rango:index'))
            
            # increment the views field of this page, and save
            page.views = page.views + 1
            page.save()
        except:
            return redirect(reverse('rango:index'))
        return redirect(page.url)

def search(request):
    result_list = []
    query = ""
    if request.method == 'POST':
        # search engine selection
        selection = request.POST['search-selection']
        print(selection)
        # user query string
        query = request.POST['query'].strip()
        if query:
            if selection == "Bing":
                # run our bing func to get the results list
                result_list = run_query(query)
            else:
                result_list = run_google_search(query)

    return render(request, 'rango/search.html', {'result_list': result_list,'query':query})

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:

templates/rango/add_category.html
{% extends 'rango/base.html' %}


{% block title_block %}
    Add a Category
{% endblock %}


{% block body_block %}

<div class="jumbotron p-4">
    <div class="container">
        <h1 class="jumbotron-heading">Add a Category</h1>
    </div>

</div>

<div class="container">
    <div class="row">
        <form action="{% url 'rango:add_category' %}" method="POST" id="category_form" role="form">
        {% csrf_token %}
        {% for hidden in form.hidden_fields %}
            {{hidden}}
        {% endfor %}
        {% for field in form.visible_fields %}
            {{ field.errors }}
            {{ field.help_text }}
            {{ field }}
            <div class="p-2"></div>
        {% endfor %}
        <br />
        <button class="btn btn-primary" type="submit" name="submit">
            Add Category
        </button>
        <div class="p-5"></div>
        </form>
    </div>
   
</div>
{% endblock %}

<!-- <form action="rango/add_category/" id="category_form" method="POST">
    {% csrf_token %}
    {% for hidden in form.hidden_fields %}
        {{hidden}}
    {% endfor %}
    {% for field in form.visible_fields %}
        {{ field.errors }}
        {{ field.help_text }}
        {{ field }}
    {% endfor %}
    <input type="submit" name="submit" value="Create Category" />
</form> -->


<!-- <!DOCTYPE html>
<html>
<head>    
    <title>Rango</title>
</head>

<body>
    <h1>Add a Category</h1>    
    <div>
        <form id="category_form" action="/rango/add_category/" method="post">
            {% csrf_token %}
            {% for hidden in form.hidden_fields %}
                {{ hidden }}
            {% endfor %}
            {% for field in form.visible_fields %}
                {{ field.errors }}
                {{ field.help_text }}
                {{ field }}
            {% endfor %}
            <input type="submit" name="submit" value="Create Category" />
        </form>
    </div>
</body>
</html> -->

templates/rango/base-old.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
    <head lang="en">
        <meta charset="UTF-8">
        <title>Rango -
            {% block title_block %}
                How to Tango with Django!
            {% endblock %}
        </title>
    </head>
    <body>
        <!-- Content -->
        <div>
            {% block body_block %}
            {% endblock %}
                
        </div>
        <div>
            {% block sidebar_block %}
                {% get_category_list category %}
            {% endblock  %}
        </div>
        <br />
        <div>
            <ul>
                {% if user.is_authenticated %}
                <li><a href="{% url 'rango:restricted' %}">Restricted Page</a></li>
                <li><a href="{% url 'auth_logout' %}?next={% url 'rango:index' %}">Logout</a></li>
                <li><a href="{% url 'rango:add_category' %}">Add a New Category</a></li>
                <li><a href="{% url 'auth_password_change' %}">Change Password</a></li>

                {% else %}
                <li><a href="{% url 'registration_register' %}">Sign Up</a></li>
                <li><a href="{% url 'auth_login' %}">Login</a></li>
                {% endif %}                
                <li><a href="{% url 'rango:about' %}">About</a></li>
                <li><a href="{% url 'rango:index' %}">Index</a></li>
            </ul>
        </div>
    </body>
</html>

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}
<html lang="en">
    <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <link rel="icon" href="{% static 'images/favicon.ico' %}">
   
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>
        Rango - {% block title_block %}How to Tango with Django!{% endblock %}
    </title>
    
    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">
    
    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.css" rel="stylesheet">

    </head>

    <body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">
                <a class="navbar-brand p-2" href="{% url 'rango:index' %}">Rango</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:index' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:about' %}">About</a></li>
                        {% if user.is_authenticated %}
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:restricted' %}">Restricted</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_logout' %}?next=/rango/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'rango:add_category' %}">Add Category</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'auth_password_change' %}">Change Password</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:search' %}">Search</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:profile' user.username %}">Profile</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'rango:list_profiles' %}">List Profiles</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'registration_register' %}">Register Here</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'auth_login' %}">Login</a></li>
                        {% endif %}
                    </ul>
                </div>
            </nav>
        </header>
        
        <div class="container-fluid" >
            <div class="row">
                <nav class="col-md-2 d-none d-md-block bg-light sidebar">
                    <div class="w-75 ml-3">
                        <input type="search"
                        id="search-input"
                        class="form-control ds-input"
                        placeholder="Search..."/>
                    </div>

                    <div class="sidebar-sticky" id="categories-listing">
                    {% block sidebar_block %}
                        {% get_category_list category %}
                    {% endblock %}
                    </div>
                </nav>
                
                <main role="main" class="col-md-9  ml-sm-auto col-lg-10 px-4">		
                    {% block body_block %}{% endblock %}
                    
                    <!-- FOOTER -->
                    <footer>
                        <p class="float-right"><a href="#">Back to top</a></p>
                        <p>&copy; 2020 Tango With Django 2 &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
                    </footer>
                </main>
            </div>
        </div>
        
        <!-- Bootstrap core JavaScript -->
        <!-- Placed at the end of the document so the pages load faster -->
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="{% static 'js/jquery-3.3.1.min.js' %}" crossorigin="anonymous">
        </script>
        
        <script src="{% static 'js/rango-jquery.js' %}" crossorigin="anonymous">
        </script>
        <!-- AJAX -->
        <script src="{% static 'js/rango-ajax.js' %}" crossorigin="anonymous">
        </script>
        <script src="{% static 'js/static rango-ajax.js' %}" crossorigin="anonymous">
        </script>

        <script>window.jQuery || document.write('<script src="https://getbootstrap.com/docs/4.2/assets/js/vendor/jquery-slim.min.js"><\/script>')</script><script src="https://getbootstrap.com/docs/4.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-zDnhMsjVZfS3hiP7oCBRmfjkQC4fzxVxFhBx8Hkz2aZX8gEvA/jsP3eXRCvzTofP" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
        <script src="https://getbootstrap.com/docs/4.2/examples/dashboard/dashboard.js"></script>

    </body>
</html>

templates/rango/categories.html
<ul class="nav flex-column">
    {% if categories %}
        {% for c in categories %}
            {% if c == current_category %}
            <li class="nav-item">
                <a class="nav-link active" href="{% url 'rango:show_category' c.slug %}"><span data-feather="archive"></span>{{ c.name }}</>
            </li>
            {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'rango:show_category' c.slug %}"><span data-feather="archive"></span>{{c.name}}</a>
            </li>
            {% endif %}
        {% endfor %}
    {% else %}
        <li><strong>There are no categories present.</strong></li>
    {% endif %}
</ul>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
    {% if category %}
        {{ category.name }}
    {% else %}
        Unknown Category
    {% endif %}
{% endblock %}


{% block body_block %}
    
<div class="jumbotron p-4">
    <div class="container">
        {% if category %}
        <h1>{{ category.name}}</h1>
        <div>
            <strong id="like_count">{{ category.likes }}</strong> likes
            {% if user.is_authenticated %}
            <button id="like_btn"
            data-categoryid="{{ category.id }}"
            class="btn btn-primary btn-sm"
            type="button">
            <!-- icon -->
            <span data-feather="thumbs-up"></span>
            Like Category
            </button>
            {% endif %} 
        </div>
        {% endif %}
            
        {% if pages %}
            <ul>
                {% for page in pages %}
                    <li><a href="{% url 'rango:goto' %}?page_id={{page.id}}">{{ page.title }}</a>
                    
                    {% if page.views <= 1 %}
                        <p>view: {{page.views}}</p>
                    {% else %}
                        <p>views: {{page.views}}</p>
                    {% endif %}
                        
                    </li>
                {% endfor %}
            </ul>        
        {% else %}
        <strong>No pages currently in category.</strong> 
        {% endif %}
    </div>
</div>

{% if user.is_authenticated %}
        
    <a href="{% url 'rango:add_page' category.slug %}">Add Page</a>
    <!-- query section -->
    <div>
        <form class="form-inline" id="user-form" method="POST" action="{% url 'rango:show_category' category.slug %}">
            {% csrf_token %}
            <div class="form-group">
                <select name="search_engine" id="search_engine" value="site">
                    <option value="site">site</option>
                    <option value="bing">Bing</option>
                </select>
                <input class="form-group" size="50" name="query" id="query" type="text" placeholder="{{query}}" />
            </div>

            <button class="btn btn-primary" type="submit" name="submit" data-categoryid="{{category.slug}}" id="search_id">Search</button>
        </form>
    </div>

    <div class="container">
        <!-- better to perform ajax to render the results -->
        {% if category_query or result_list %}
            <h2>Results</h2>
            <div class="list-group" id="display">
                
                {% for result in category_query %}
                <div class="list-group-item">
                        <h3 class="list-group-item-heading">
                            <a href="{% url 'rango:show_category' result.slug %}">
                                {{result|safe|escape}}
                            </a>
                        <button class="btn btn-info btn-sm rango-page-add"
                        type="button"
                        data-categoryid="{{ category.id }}"
                        data-title="{{ result.title }}"
                        data-url="{{ result.link }}">
                        Add
                        </button>
                        </h3>
                        
                        {% for page in pages_query %}
                        {% if page.category == result %}
                        <p class="list-group-item" id="page-listing">
                            <a href="{% url 'rango:goto' %}?page_id={{page.id}}">
                                {{page}}
                                {{page.title|safe|escape}}
                            </a>
                            <br>
                            {% if page.views > 1 %}
                            {{ page.views }} views
                            {% elif page.views <= 1 %}
                            {{ page.views }} view
                            {% endif %}
                        </p>
                            
                        {% endif %}
                            
                        {% endfor %}
                    </div>
                {% endfor %}
                
                {% for result in result_list  %}
                <div class="list-group-item">
                    <h3 class="list-group-item-heading">
                        <a href="{{result.link}}">
                            {{result.title|safe|escape}}
                        </a>
                        
                        <button class="btn btn-info btn-sm rango-page-add"
                        type="button"
                        data-categoryid="{{ category.id }}"
                        data-title="{{ result.title }}"
                        data-url="{{ result.link }}">
                        Add
                        </button>
                    </h3>
                    <p class="list-group-item">
                        {{result.summary|safe|escape}}
                    </p>
                </div>
                {% endfor %}
                    
            </div>
        {% else %}
            <strong>The specified category does not exist.</strong>
            <br />
        {% endif %}
    </div>
{% endif %}

{% endblock %}